### ISSUE TITLE
undefined reference to `GDALCreateOverviewDataset(GDALDataset*, int, int)'

### ISSUE THREAD

**Issue by ghorn** [meteogrid/bindings-gdal#8]
```
$ gdal-config --version
2.2.1

$ stack build --flag bindings-gdal:examples
bindings-gdal-2.1.1.1: build (lib + exe)
Preprocessing library bindings-gdal-2.1.1.1...
Preprocessing executable 'ogrinfo-hs' for bindings-gdal-2.1.1.1...
Preprocessing executable 'rasterstats-hs' for bindings-gdal-2.1.1.1...
Linking .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/rasterstats-hs/rasterstats-hs ...
/home/greghorn/hslibs/bindings-gdal/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/libHSbindings-gdal-2.1.1.1-4fDT7HjJSKi7IYJavM3faa.a(overviews.o): In function `hs_gdal_create_overview_dataset':

/home/greghorn/hslibs/bindings-gdal/cbits/overviews.cpp:41:0: error:
     undefined reference to `GDALCreateOverviewDataset(GDALDataset*, int, int)'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package bindings-gdal-2.1.1.1 using:
      /home/greghorn/hslibs/bindings-gdal/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0 build lib:bindings-gdal exe:ogrinfo-hs exe:rasterstats-hs --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

Any clue why this is happening? An older version of `bindings-gdal` works fine for me.

**Comment by albertov** [comment]
It seems like a linker issue. I had a similar error when upgrading to ghc-8.2.1. What version of ghc are you using? Also, are you building with this commit applied: 0f6bf32e9470d7267765cab6154e41d6f80d3efd?

**Comment by ghorn** [comment]
I'm using ghc-8.0.2 via stackage LTS-9.1. I'm on master which is currently aecc2fcb4b40bf88aaf3761812a0ed36f57fd259 so I do have that commit applied. It is specifically that function because if I comment it out, I don't get the linker error. Could this be related to your

`//FIXME: Use GdalOpenEx instead of the GDALCreateOverviewDataset private API` ?

Maybe that symbol is not exported for my platform?

**Comment by albertov** [comment]
> Maybe that symbol is not exported for my platform?

I'm pretty sure this is the problem. Perhaps we should remove this binding from the library until it gets fixed?
